# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170706_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bevetel',
            old_name='eladas_datum',
            new_name='bevetel_datum',
        ),
    ]
