# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170706_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termek',
            name='mennyiseg',
        ),
        migrations.AlterField(
            model_name='raktarkeszlet',
            name='keszlet',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='raktarkeszlet',
            unique_together=set([('termek', 'raktar')]),
        ),
    ]
