# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170706_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bevetel',
            name='bevetel_mennyiseg',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ertekesit',
            name='eladas_mennyiseg',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='raktarkeszlet',
            name='keszlet',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
