# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170711_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bevetel',
            name='ar_bevetel_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='termek',
            name='ar_web_netto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
